version: '3'

services:
  web:
    build: .
    command: python setup/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: teste
      POSTGRES_USER: jvfff
      POSTGRES_PASSWORD: panda
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
