# Generated by Django 5.0.7 on 2024-08-13 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_userprofile_cep_userprofile_cpf_userprofile_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('tipo_gramado', models.CharField(choices=[('natural', 'Natural'), ('sintetico', 'Sintético')], max_length=255)),
                ('iluminacao', models.BooleanField(default=False)),
                ('vestiarios', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
