# Generated by Django 5.0.7 on 2024-08-14 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0004_campo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='campo',
            old_name='cidade',
            new_name='localizacao',
        ),
        migrations.RemoveField(
            model_name='campo',
            name='endereco',
        ),
        migrations.AddField(
            model_name='campo',
            name='capacidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campo',
            name='comprimento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Em metros', max_digits=5),
        ),
        migrations.AddField(
            model_name='campo',
            name='descricao_adicional',
            field=models.TextField(blank=True, help_text='Informações adicionais sobre o campo', null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='disponibilidade',
            field=models.TextField(blank=True, help_text='Informe os dias e horários disponíveis', null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='facilidades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='campos/fotos/'),
        ),
        migrations.AddField(
            model_name='campo',
            name='largura',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Em metros', max_digits=5),
        ),
        migrations.AddField(
            model_name='campo',
            name='preco_por_dia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço por dia em R$ (opcional)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='preco_por_hora',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Preço por hora em R$', max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campo',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='campo',
            name='status',
            field=models.CharField(default='pendente', max_length=50),
        ),
        migrations.AlterField(
            model_name='campo',
            name='tipo_gramado',
            field=models.CharField(choices=[('natural', 'Natural'), ('sintetico', 'Sintético')], max_length=50),
        ),
        migrations.AlterField(
            model_name='campo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campo',
            name='vestiarios',
            field=models.IntegerField(),
        ),
    ]
