# Generated by Django 5.0.7 on 2024-08-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0006_campo_latitude_campo_longitude_alter_campo_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='dias_disponiveis',
            field=models.TextField(blank=True, help_text='Dias disponíveis para aluguel (separados por vírgula)', null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='horarios_disponiveis',
            field=models.TextField(blank=True, help_text='Horários disponíveis para aluguel (separados por vírgula)', null=True),
        ),
    ]
