# Generated by Django 5.0.7 on 2024-08-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0008_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='horario',
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo_reserva',
            field=models.CharField(choices=[('hora', 'Por Hora'), ('dia', 'Por Dia')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
