# Generated by Django 5.0.7 on 2024-09-03 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0010_avaliacao'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together=set(),
        ),
    ]
