# Generated by Django 5.0.7 on 2024-09-03 14:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0011_alter_avaliacao_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('campo', 'usuario')},
        ),
    ]
